# Source location
SRCDIR = /CTSM/cime/src/externals/mct
FDEPENDS=$(SRCDIR)/fdepends.awk

# COMPILER, LIBRARY, AND MACHINE MAKE VARIABLES

# FORTRAN COMPILER VARIABLES #

# FORTRAN COMPILER COMMAND
FC		= mpif90 

# FORTRAN AND FORTRAN90 COMPILER FLAGS
FCFLAGS		=   -fconvert=big-endian -ffree-line-length-none -ffixed-line-length-none   -O    -ffree-form  -I. -I/output/restructure-ctsm-ozone-luna-sunnivin-1x1brazil.fates.docker.Cd08b750-F5534a94/bld/gnu/openmpi/nodebug/nothreads/mct/include -I/output/restructure-ctsm-ozone-luna-sunnivin-1x1brazil.fates.docker.Cd08b750-F5534a94/bld/gnu/openmpi/nodebug/nothreads/mct/mct/noesmf/c1a1l1i1o1r1g1w1i1e1/include -I/output/restructure-ctsm-ozone-luna-sunnivin-1x1brazil.fates.docker.Cd08b750-F5534a94/bld/gnu/openmpi/nodebug/nothreads/mct/finclude -I/usr/local/netcdf/include -I/output/restructure-ctsm-ozone-luna-sunnivin-1x1brazil.fates.docker.Cd08b750-F5534a94/bld/gnu/openmpi/nodebug/nothreads/mct/include 

FC_DEFINE = -D

# FORTRAN COMPILE FLAG FOR AUTOPROMOTION
# OF NATIVE REAL TO 8 BIT REAL
REAL8           = 

# FORTRAN COMPILE FLAGS FOR EXAMPLE PROGRAMS
PROGFCFLAGS = 

# FORTRAN COMPILE FLAG FOR CHANGING BYTE ORDERING
ENDIAN          = 

# INCLUDE FLAG FOR LOCATING MODULES (-I, -M, or -p)
INCFLAG         = -I

# INCLUDE PATHS (PREPEND INCLUDE FLAGS -I, -M or -p)
INCPATH         =  

# MPI LIBRARIES (USUALLY -lmpi)
MPILIBS         = 

# PREPROCESSOR VARIABLES #

# COMPILER AND OS DEFINE FLAGS
CPPDEFS =  -Dlinux  -DCESMCOUPLED   -DFORTRANUNDERSCORE -DNO_R16 -DCPRGNU -DNDEBUG -DHAVE_MPI -DMCT_INTERFACE -DPIO1 -DATM_PRESENT -DICE_PRESENT -DLND_PRESENT -DOCN_PRESENT -DROF_PRESENT -DGLC_PRESENT -DWAV_PRESENT -DESP_PRESENT -DMED_PRESENT -DSYSLINUX -DCPR

FPPDEFS=$(patsubst -D%,$(FC_DEFINE)%,$(CPPDEFS))

# C COMPILER VARIABLES #

# C COMPILER
CC		= mpicc  

# C COMPILER FLAGS - APPEND CFLAGS
CFLAGS       = -std=gnu99   -O   -Dlinux  -DCESMCOUPLED   -DFORTRANUNDERSCORE -DNO_R16 -DCPRGNU -DNDEBUG -DHAVE_MPI -DMCT_INTERFACE -DPIO1 -DATM_PRESENT -DICE_PRESENT -DLND_PRESENT -DOCN_PRESENT -DROF_PRESENT -DGLC_PRESENT -DWAV_PRESENT -DESP_PRESENT -DMED_PRESENT -I.. -I. -I/output/restructure-ctsm-ozone-luna-sunnivin-1x1brazil.fates.docker.Cd08b750-F5534a94/bld/gnu/openmpi/nodebug/nothreads/mct/include -I/output/restructure-ctsm-ozone-luna-sunnivin-1x1brazil.fates.docker.Cd08b750-F5534a94/bld/gnu/openmpi/nodebug/nothreads/mct/mct/noesmf/c1a1l1i1o1r1g1w1i1e1/include -I/output/restructure-ctsm-ozone-luna-sunnivin-1x1brazil.fates.docker.Cd08b750-F5534a94/bld/gnu/openmpi/nodebug/nothreads/mct/finclude -I/usr/local/netcdf/include -I/output/restructure-ctsm-ozone-luna-sunnivin-1x1brazil.fates.docker.Cd08b750-F5534a94/bld/gnu/openmpi/nodebug/nothreads/mct/include
CPPFLAGS = 

# LIBRARY SPECIFIC VARIABLES #

# USED BY MCT BABEL BINDINGS
COMPILER_ROOT = 
BABELROOT     = 
PYTHON        = 
PYTHONOPTS    = 

# USED BY MPI-SERIAL LIBRARY

# SIZE OF FORTRAN REAL AND DOUBLE
FORT_SIZE = 


# INSTALLATION VARIABLES #

# INSTALL COMMANDS
INSTALL         = /output/restructure-ctsm-ozone-luna-sunnivin-1x1brazil.fates.docker.Cd08b750-F5534a94/bld/gnu/openmpi/nodebug/nothreads/mct/mct/install-sh -c
MKINSTALLDIRS   = /output/restructure-ctsm-ozone-luna-sunnivin-1x1brazil.fates.docker.Cd08b750-F5534a94/bld/gnu/openmpi/nodebug/nothreads/mct/mct/mkinstalldirs

# INSTALLATION DIRECTORIES
abs_top_builddir= /output/restructure-ctsm-ozone-luna-sunnivin-1x1brazil.fates.docker.Cd08b750-F5534a94/bld/gnu/openmpi/nodebug/nothreads/mct/mct
MCTPATH         = /output/restructure-ctsm-ozone-luna-sunnivin-1x1brazil.fates.docker.Cd08b750-F5534a94/bld/gnu/openmpi/nodebug/nothreads/mct/mct/mct
MPEUPATH        = /output/restructure-ctsm-ozone-luna-sunnivin-1x1brazil.fates.docker.Cd08b750-F5534a94/bld/gnu/openmpi/nodebug/nothreads/mct/mct/mpeu
EXAMPLEPATH     = /output/restructure-ctsm-ozone-luna-sunnivin-1x1brazil.fates.docker.Cd08b750-F5534a94/bld/gnu/openmpi/nodebug/nothreads/mct/mct/examples
MPISERPATH      = 
libdir          = /usr/local/lib
includedir      = /usr/local/include

# OTHER COMMANDS #
RANLIB		= ranlib
AR		= ar cq
RM		= rm -f





